# Generated by Django 4.2.20 on 2025-05-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='slug',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='type',
            field=models.CharField(default=1, help_text='Type of news article (e.g., Press Release, Blog Post, Event)', max_length=100),
            preserve_default=False,
        ),
    ]
