# Generated by Django 4.2.20 on 2025-05-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_newsarticle_slug_newsarticle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for the image', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='summary',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='image',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='main_image',
            field=models.ImageField(default=1, help_text='Main image for thumbnails and previews', upload_to='news/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='news_articles', to='news.newsimage'),
        ),
    ]
