# Generated by Django 4.2.20 on 2025-04-25 16:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('responsibilities', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('closing_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_names', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('current_address', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('previous_employer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_employer_address', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_employer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_start_date', models.DateField(blank=True, null=True)),
                ('employment_end_date', models.DateField(blank=True, null=True)),
                ('employment_duties', models.TextField(blank=True, null=True)),
                ('education_level', models.CharField(choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=20)),
                ('institution_name', models.CharField(max_length=200)),
                ('course_of_study', models.CharField(max_length=200)),
                ('education_start_date', models.DateField()),
                ('education_end_date', models.DateField()),
                ('qualification_grade', models.CharField(max_length=50)),
                ('professional_institution_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('professional_start_date', models.DateField(blank=True, null=True)),
                ('professional_end_date', models.DateField(blank=True, null=True)),
                ('professional_qualification_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('declaration_agreement', models.BooleanField(default=False)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('job_advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobadvertisement')),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
    ]
