# Generated by Django 5.0.6 on 2024-11-14 16:24

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sbcapp1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobadvertisement",
            name="date_posted",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="jobadvertisement",
            name="deadline_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
