# Generated by Django 4.2.20 on 2025-05-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_product_name_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='company_name',
        ),
    ]
