# Generated by Django 4.2.20 on 2025-05-20 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('business_address', models.TextField()),
                ('id_document', models.FileField(upload_to='partners/id_documents/')),
                ('business_license', models.FileField(upload_to='partners/business_licenses/')),
                ('tax_certificate', models.FileField(blank=True, null=True, upload_to='partners/tax_certificates/')),
                ('experience', models.CharField(choices=[('0-1', 'Less than 1 year'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5+', 'More than 5 years')], max_length=5)),
                ('distribution_area', models.CharField(help_text='Geographic area you plan to distribute in', max_length=255)),
                ('existing_customers', models.TextField(blank=True, help_text='List of existing customers or market segments')),
                ('storage_capacity', models.CharField(help_text='Available storage capacity', max_length=255)),
                ('why_partner', models.TextField(help_text='Why do you want to become a distributor?')),
                ('additional_info', models.TextField(blank=True, help_text="Any additional information you'd like to share")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Distributor Application',
                'verbose_name_plural': 'Distributor Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
