# Generated by Django 4.2.20 on 2025-05-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerapplication',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='partnerapplication',
            old_name='id_document',
            new_name='id_back',
        ),
        migrations.RemoveField(
            model_name='partnerapplication',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='partnerapplication',
            name='existing_customers',
        ),
        migrations.RemoveField(
            model_name='partnerapplication',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='partnerapplication',
            name='storage_capacity',
        ),
        migrations.RemoveField(
            model_name='partnerapplication',
            name='why_partner',
        ),
        migrations.AddField(
            model_name='partnerapplication',
            name='id_front',
            field=models.FileField(default=1, upload_to='partners/id_documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerapplication',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
