# Generated by Django 4.2.20 on 2025-05-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_rename_full_name_partnerapplication_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerapplication',
            name='business_address',
        ),
    ]
