# Generated by Django 4.2.20 on 2025-04-25 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('submission_guidelines', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='tender_documents/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('awarded', 'Awarded')], default='open', max_length=10)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('closing_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
