# Generated by Django 4.2.20 on 2025-05-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_date']},
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='course_of_study',
            new_name='applicant_name',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='application_date',
            new_name='applied_date',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='employment_duties',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='full_names',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='resume',
            new_name='resume_url',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='declaration_agreement',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='education_end_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='education_start_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='employment_end_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='employment_start_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='previous_employer_address',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='previous_employer_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='previous_employer_phone',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='professional_end_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='professional_institution_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='professional_qualification_grade',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='professional_start_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='qualification_grade',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('interviewed', 'Interviewed'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
