# Generated by Django 5.2.1 on 2025-06-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_jobadvertisement_department_jobadvertisement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvertisement',
            name='type',
            field=models.TextField(),
        ),
    ]
