# Generated by Django 5.2.1 on 2025-06-05 10:28

import recruitment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_alter_jobadvertisement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_url',
            field=models.FileField(blank=True, help_text='Upload your resume (PDF or Word document, max 5MB)', null=True, upload_to=recruitment.models.resume_upload_path),
        ),
    ]
