# Generated by Django 4.2.20 on 2025-04-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text="Font Awesome icon class (e.g., 'fab fa-facebook')", max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display the link')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
