# Generated by Django 5.2.1 on 2025-06-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tender',
            old_name='requirements',
            new_name='additionalInfo',
        ),
        migrations.RenameField(
            model_name='tender',
            old_name='closing_date',
            new_name='closingDate',
        ),
        migrations.RenameField(
            model_name='tender',
            old_name='reference_number',
            new_name='tenderNumber',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='submission_guidelines',
        ),
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('awarded', 'Awarded')], default='open', max_length=20),
        ),
    ]
