# Generated by Django 4.2.20 on 2025-05-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbcapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Staff'), (3, 'Distributor'), (4, 'Customer')], default=4),
        ),
    ]
