# Generated by Django 4.2.20 on 2025-05-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbcapp', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Sales'), (4, 'HR'), (3, 'Distributor'), (4, 'Customer')], default=4),
        ),
    ]
