# Generated by Django 4.2.20 on 2025-05-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbcapp', '0004_alter_customuser_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Sales'), (3, 'Distributor'), (4, 'Customer'), (5, 'HR')], default=4),
        ),
    ]
