# Generated by Django 4.2.16 on 2025-08-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbcapp', '0006_alter_customuser_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Sales'), (3, 'Distributor'), (4, 'Customer'), (5, 'HR'), (6, 'Procurement'), (7, 'Receptionist')], default=4),
        ),
    ]
