# Generated by Django 4.2.20 on 2025-05-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('distributor', 'Distributor'), ('supermarket', 'Supermarket'), ('pharmacy', 'Pharmacy'), ('other', 'Other')], max_length=50)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Distributor Contact',
                'verbose_name_plural': 'Distributor Contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
