# Generated by Django 4.2.20 on 2025-05-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_distributorcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorcontact',
            name='business_type',
            field=models.CharField(max_length=100),
        ),
    ]
